Teamchong/add loading indicator to table
EventStore/Design-System pull request #366
Opened 2024-05-15 22:57 UTC by teamchong

Improvements:

- The `renderLoadingState` prop in the `Page` component now accepts false as a parameter, which will render the component normally.
- A new prop `loading` has been added to `es-table` to indicate if `cell.loading` should be used for rendering cells. Additionally, `loadingRows` has been introduced to specify the number of rows to render when `loading` is `true`, defaulting to `1`.

Bug fixes:

- Removed `fixStyle: 'inline-type-imports'` from the ESLint rules section, as the latest version of `@typescript-eslint/consistent-type-imports` no longer supports it.

2024-05-16 08:06 UTC, George-Payne requested changes

2024-05-16 08:06 UTC, George-Payne commented on packages/components/src/components/tables/es-table/es-table.tsx
> +                            })}
Do we want a default loading, so we don't need to pass it everywhere?

```tsx
<es-loading-text expectedLength={cell.title?.length ?? 30} />
```

Would probably be a sensible default. 

Or we could add `expectedLength` to the `TableCell` definition and have:

```tsx
<es-loading-text expectedLength={cell.expectedLength ?? cell.title?.length ?? 30} />
```

So now a table definition can be as before:

```tsx
name: { title: 'User Name' },
```

If it has a known expected length:
```tsx
id: { 
    title: 'Project Id',
    expectedLength: 20,
},
```

If you want to do something fancy:
```tsx
fancy: { 
    title: 'Something fancy',
    loading: () => "I am loading!",
},
```

We could then disable a loading cell as needed with `() => null`

2024-05-16 08:06 UTC, George-Payne commented on packages/components/src/components/tables/es-table-detail/es-table-detail.tsx
> +                                {!this.renderCell(name, cell, loading)}
Why `!`?

2024-05-17 09:43 UTC, George-Payne requested changes
Looks like you need to run prettier also

2024-05-17 09:43 UTC, George-Payne commented on packages/components/src/components/tables/es-table/es-table.tsx
> +                                <es-es-loading-text
Double `es-`

2024-05-17 09:43 UTC, George-Payne commented on packages/components/src/components/tables/es-table/es-table.tsx
> +                            cell.width !== '0' &&
Having a 0 width cell is very unusual (and was basically a hack on the organizations overview to fit two data shapes on a single table), I don't think it's worth having a special case for it here, when we can just add `loading: () => null` in that one place.

2024-05-17 09:43 UTC, George-Payne commented on packages/components/src/components/tables/es-table/es-table.tsx
>                          {!this.loading && cell.cell
Just spotted that this is wrong, and will auto-extract on loading.

2024-05-17 09:43 UTC, George-Payne commented on packages/components/src/components/tables/es-table/es-table.tsx
> +                                    exectedLength={cell.title?.length ?? 30}
```suggestion
                                    expectedLength={cell.title?.length ?? 30}
```

2024-05-17 09:43 UTC, George-Payne commented on packages/components/src/components/tables/es-table/es-table.tsx
> +                            ))}
This entire section section has gotten a bit hard to read, probably time to split it out:

```tsx
    renderCell = (
        cell: TableCell<unknown>,
        name: string,
        key: string,
        data: unknown,
    ) => {
        if (this.loading) {
            if (cell.loading == null) {
                return (
                    <es-loading-text
                        expectedLength={cell.title?.length ?? 30}
                    />
                );
            }

            return cell.loading(h, {
                key,
                data,
                parent: this.identifier,
            });
        }

        if (cell.cell == null) {
            return autoExtract(data, name);
        }

        return cell.cell(h, {
            ...(this.extraCellProps?.(key, data) ?? {}),
            key,
            data,
            parent: this.identifier,
        });
    };
```

2024-05-17 09:43 UTC, George-Payne commented on packages/components/src/components/tables/es-table/es-table.tsx
>                  {!this.loading && this.rows?.map(this.renderRowGroup)}
Still think this would be clearer as a ternary, rather than checking `this.loading` twice.

2024-05-22 20:29 UTC, teamchong commented
To test with `bespin`, I have added the following to the root `package.json` in the `bespin` repository:

```json
"resolutions": {
    "@eventstore-ui/components": "portal:/home/teamchong/repos/Design-System/packages/components",
    "@eventstore-ui/layout": "portal:/home/teamchong/repos/Design-System/packages/layout"
}
```

I have also included the following userscript to assist with testing:

```ts
// ==UserScript==
// @name         Test loading indicators
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  Add a delay to test loading indicators
// @author       teamchong
// @match        https://console.bespin.dev/*
// @grant        GM_registerMenuCommand
// @grant        GM_notification
// @grant        unsafeWindow
// ==/UserScript==

(function() {
    'use strict';
    const delaySet = new URLSearchParams(location.search).get('delay');
    const delay = delaySet ? parseInt(delaySet, 10) ?? 5000 : 5000;
    const tests = [
        ['organizations', '/organizations', /\/resources\/v1\/organizations/],
        ['groups', '/organizations/bqjlpkug10l3jdar2e1g/access-control\/groups', /\/access\/v1\/organizations\/.+\/groups/],
        ['invitations', '/organizations/bqjlpkug10l3jdar2e1g/access-control/invitations', /\/access\/v1\/organizations\/.+\/invites/],
        ['members', '/organizations/bqjlpkug10l3jdar2e1g/access-control\/members', /\/access\/v1\/organizations\/.+\/members/],
        ['policies', '/organizations/bqjlpkug10l3jdar2e1g/access-control\/policies', /\/access\/v1\/organizations\/.+\/policies/],
        ['authentication-tokens', '/authentication-tokens', /\/access\/v1\/tokens\/user/],
        ['issues', '/events-console/issues', /\/events\/v1\/issues/],
        ['notifications', '/events-console/notifications', /\/events\/v1\/notifications/],
        ['scheduled-backups', '/organizations/bqjlpkug10l3jdar2e1g/projects/brcs88ug10l3o051p2pg/jobs\/scheduled-backups', /\/orchestrate\/v1\/organizations\/.+\/projects\/.+\/jobs/],
        ['projects', '/organizations/bqjlpkug10l3jdar2e1g/projects', /\/resources\/v1\/organizations\/.+\/projects/],
        ['clusters', '/organizations/bqjlpkug10l3jdar2e1g/projects/brcs88ug10l3o051p2pg/managed-esdb/clusters', /\/mesdb\/v1\/organizations\/.+\/projects\/.+\/clusters/],
        ['integrations', '/organizations/bqjlpkug10l3jdar2e1g/projects/brcs88ug10l3o051p2pg/integrations', /\/integrate\/v1\/organizations\/.+\/projects\/.+\/integrations/],
        ['backups', '/organizations/bqjlpkug10l3jdar2e1g/projects/brcs88ug10l3o051p2pg/managed-esdb/backups', /\/mesdb\/v1\/organizations\/.+\/projects\/.+\/backups/],
        ['networks', '/organizations/bqjlpkug10l3jdar2e1g/projects/brcs88ug10l3o051p2pg/networks', /\/infra\/v1\/organizations\/.+\/projects\/.+\/networks/],
        ['peerings', '/organizations/bqjlpkug10l3jdar2e1g/projects/brcs88ug10l3o051p2pg/peerings', /\/infra\/v1\/organizations\/.+\/projects\/.+\/peerings/],
    ];
    let delayed = false;
    tests.forEach(([name, href]) => GM_registerMenuCommand(`Test ${name}`, () => Object.assign(location, {
        href: `${href}?t=${new Date().getTime()}${delaySet ? `&delay=${delaySet}` : ''}`
    })));

    const originalFetch = unsafeWindow.fetch;
    const matches = tests.map(([_, href, api]) => [new RegExp(`${href.replace(/bqjlpkug10l3jdar2e1g|brcs88ug10l3o051p2pg/, '.+')}/?$`), api]);
    unsafeWindow.fetch = function(...args) {
        const url = args[0];
        const shouldDelay = typeof url === 'string' && matches.some(([m, api]) => m.test(location.pathname) && !!api && api.test(url));

        if (shouldDelay) {
            return new Promise((resolve) => {
                GM_notification({
                    text: url,
                    title: `Delay ${delay}`,
                    timeout: delay,
                });
                setTimeout(() => originalFetch(...args).then(resolve), delay);
            });
        } else {
            return originalFetch(...args);
        }
    };
})();
```

Below is a demo of the testing:

https://github.com/EventStore/Design-System/assets/25894545/a30d8a15-d87a-4e4f-939c-12c43d4a2b09

2024-05-24 12:56 UTC, George-Payne commented on packages/components/src/components.d.ts
> +    interface EsProgressionDemo {
On of the issues with the demos, is you then need to run `yarn build` before commiting, to not have them in this `components.d.ts`.

2024-05-27 12:21 UTC, George-Payne requested changes

2024-05-27 12:21 UTC, George-Payne commented on packages/components/src/components/tables/es-table-detail/es-table-detail.tsx
> +    };
Seem to have lost the `<dd>`, so it's no-longer a valid datalist.

2024-05-27 12:21 UTC, George-Payne commented on packages/components/src/components/tables/es-table-detail/es-table-detail.tsx
> +                                {this.renderCell(name)}
Probably simpler to add  it back here:
Probably simpler to add it here, and remove the `renderHeader` func.

```suggestion
                                <dt>{title}</dt>
                                <dd>{this.renderCell(name)}</dd>
```

2024-05-27 12:25 UTC, George-Payne approved these changes

2024-05-28 12:04 UTC, merged